# Generated by Django 5.2.7 on 2026-03-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'banco',
                'verbose_name_plural': 'bancos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('comissao_percentual', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='comissão percentual')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDeSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'categoria de despesa',
                'verbose_name_plural': 'categorias de despesa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'forma de pagamento',
                'verbose_name_plural': 'formas de pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_admissao', models.DateField(verbose_name='data de admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='data de demissão')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='cadastros.cargo', verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='cadastros.setor', verbose_name='setor'),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('nome', 'setor')},
        ),
        migrations.CreateModel(
            name='SubcategoriaDeSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='cadastros.categoriadespesa', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'subcategoria de despesa',
                'verbose_name_plural': 'subcategorias de despesa',
                'ordering': ['categoria__nome', 'nome'],
                'unique_together': {('nome', 'categoria')},
            },
        ),
    ]
