# Generated by Django 5.2.7 on 2026-03-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='complemento',
            field=models.CharField(blank=True, max_length=120, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='documento',
            field=models.CharField(blank=True, max_length=30, verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereco'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='numero'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='uf'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='comissao percentual'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(verbose_name='data de admissao'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='data de demissao'),
        ),
    ]
