# Generated by Django 5.2.7 on 2026-03-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_colaborador_bairro_colaborador_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='salario bruto'),
        ),
    ]
