# Generated by Django 5.2.7 on 2026-03-31 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=200, verbose_name='nome completo')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('cargo', models.CharField(blank=True, max_length=120, verbose_name='cargo')),
                ('observacao', models.TextField(blank=True, verbose_name='observacao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'ordering': ['nome_completo', 'user__username'],
            },
        ),
    ]
