# Generated by Django 5.2.7 on 2026-03-31 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('ver_dashboard', models.BooleanField(default=True, verbose_name='ver dashboard')),
                ('ver_cadastros', models.BooleanField(default=True, verbose_name='ver cadastros')),
                ('ver_faturamento', models.BooleanField(default=True, verbose_name='ver faturamento')),
                ('ver_despesas', models.BooleanField(default=True, verbose_name='ver despesas')),
                ('ver_folha', models.BooleanField(default=True, verbose_name='ver folha')),
                ('ver_dre', models.BooleanField(default=True, verbose_name='ver dre')),
                ('ver_usuarios', models.BooleanField(default=False, verbose_name='ver usuarios')),
                ('ver_admin', models.BooleanField(default=False, verbose_name='ver admin')),
            ],
            options={
                'verbose_name': 'perfil de acesso',
                'verbose_name_plural': 'perfis de acesso',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_acesso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.perfilacesso', verbose_name='perfil de acesso'),
        ),
    ]
