# Generated by Django 5.2.7 on 2026-03-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='data')),
                ('valor_dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor em dinheiro')),
                ('valor_pix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor em pix')),
                ('valor_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor em crédito')),
                ('valor_debito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor em débito')),
                ('valor_fiado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor fiado')),
                ('valor_vale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor em vale')),
                ('faturamento_bar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='faturamento bar')),
                ('faturamento_cozinha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='faturamento cozinha')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
            ],
            options={
                'verbose_name': 'registro de faturamento',
                'verbose_name_plural': 'registros de faturamento',
                'ordering': ['-data'],
            },
        ),
    ]
