# Generated by Django 5.2.7 on 2026-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofaturamento',
            name='quantidade_pessoas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de pessoas'),
        ),
    ]
