# Generated by Django 5.2.7 on 2026-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_registrofaturamento_quantidade_pessoas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofaturamento',
            name='faturamento_outros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='faturamento outros'),
        ),
        migrations.AddField(
            model_name='registrofaturamento',
            name='faturamento_produtos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='faturamento produtos'),
        ),
    ]
