# Generated by Django 5.2.7 on 2026-03-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='pago')),
                ('mes_referencia', models.IntegerField(verbose_name='mês de referência')),
                ('ano_referencia', models.IntegerField(verbose_name='ano de referência')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='cadastros.banco', verbose_name='banco')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='cadastros.categoriadespesa', verbose_name='categoria')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='cadastros.formapagamento', verbose_name='forma de pagamento')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='cadastros.subcategoriadespesa', verbose_name='subcategoria')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'ordering': ['-ano_referencia', '-mes_referencia', 'descricao'],
            },
        ),
    ]
