# Generated by Django 5.2.7 on 2026-03-29 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='ano_referencia',
            field=models.IntegerField(verbose_name='ano de referencia'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='mes_referencia',
            field=models.IntegerField(verbose_name='mes de referencia'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='observacao'),
        ),
        migrations.CreateModel(
            name='RecorrenciaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('observacao', models.TextField(blank=True, verbose_name='observacao')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('data_inicio', models.DateField(verbose_name='data de inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data de termino')),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='dia de vencimento')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias_despesa', to='cadastros.banco', verbose_name='banco')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorrencias_despesa', to='cadastros.categoriadespesa', verbose_name='categoria')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias_despesa', to='cadastros.formapagamento', verbose_name='forma de pagamento')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorrencias_despesa', to='cadastros.subcategoriadespesa', verbose_name='subcategoria')),
            ],
            options={
                'verbose_name': 'recorrencia de despesa',
                'verbose_name_plural': 'recorrencias de despesa',
                'ordering': ['-data_inicio', 'descricao'],
            },
        ),
        migrations.AddField(
            model_name='despesa',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='despesas.recorrenciadespesa', verbose_name='recorrencia'),
        ),
    ]
