# Generated by Django 5.2.7 on 2026-04-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_alter_despesa_ano_referencia_alter_despesa_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='folha_tipo',
            field=models.CharField(blank=True, max_length=50, verbose_name='tipo da folha'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('FOLHA', 'Folha')], default='MANUAL', max_length=20, verbose_name='origem'),
        ),
    ]
