# Generated by Django 5.2.7 on 2026-03-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='mês')),
                ('ano', models.IntegerField(verbose_name='ano')),
                ('faturamento_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='faturamento total')),
            ],
            options={
                'verbose_name': 'período de folha',
                'verbose_name_plural': 'períodos de folha',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='DespesaTrabalhistaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FGTS', 'FGTS'), ('INSS_EMPRESA', 'INSS Empresa'), ('SEGURO_VIDA', 'Seguro de Vida Coletivo'), ('13_SALARIO_50', '13º Salário (50%)'), ('PROVISAO_13', 'Provisão 13º'), ('EXAMES', 'Exames Admissionais e Demissionais'), ('UNIFORME', 'Uniforme'), ('FERIAS_PROVISAO', 'Férias (Provisão)'), ('RESCISAO', 'Rescisão Trabalhista'), ('FGTS_RESCISAO', 'FGTS - Rescisão'), ('PRO_LABORE', 'Pro-labore'), ('SALARIO_BRUTO', 'Salário Bruto'), ('CONVENIO_SEGURO', 'Convênios e Seguros de Vida'), ('FOLGAS_DOBRAS', 'Folgas e Dobras'), ('HORAS_EXTRAS', 'Horas Extras')], max_length=30, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='pago')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_trabalhistas', to='cadastros.banco', verbose_name='banco')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_trabalhistas', to='folha.periodofolha', verbose_name='período')),
            ],
            options={
                'verbose_name': 'despesa trabalhista mensal',
                'verbose_name_plural': 'despesas trabalhistas mensais',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='salário bruto')),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INSS')),
                ('vale_consumo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='vale consumo')),
                ('salario_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='salário líquido')),
                ('adicional_noturno', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='adicional noturno')),
                ('dsr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DSR')),
                ('adiantamento_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='adiantamento')),
                ('adiantamento_data', models.DateField(blank=True, null=True, verbose_name='data do adiantamento')),
                ('adiantamento_pago', models.BooleanField(default=False, verbose_name='adiantamento pago')),
                ('saldo_final_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo final')),
                ('saldo_final_data', models.DateField(blank=True, null=True, verbose_name='data do saldo final')),
                ('saldo_final_pago', models.BooleanField(default=False, verbose_name='saldo final pago')),
                ('produtividade_1_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='produtividade 1')),
                ('produtividade_1_data', models.DateField(blank=True, null=True, verbose_name='data produtividade 1')),
                ('produtividade_1_pago', models.BooleanField(default=False, verbose_name='produtividade 1 paga')),
                ('produtividade_2_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='produtividade 2')),
                ('produtividade_2_data', models.DateField(blank=True, null=True, verbose_name='data produtividade 2')),
                ('produtividade_2_pago', models.BooleanField(default=False, verbose_name='produtividade 2 paga')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_folha', to='cadastros.colaborador', verbose_name='colaborador')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='folha.periodofolha', verbose_name='período')),
            ],
            options={
                'verbose_name': 'lançamento de colaborador',
                'verbose_name_plural': 'lançamentos de colaboradores',
                'ordering': ['colaborador__nome'],
                'unique_together': {('periodo', 'colaborador')},
            },
        ),
        migrations.CreateModel(
            name='BeneficioColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale_transporte', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='vale transporte')),
                ('ajuda_custo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='ajuda de custo')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='pago')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_folha', to='cadastros.colaborador', verbose_name='colaborador')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='folha.periodofolha', verbose_name='período')),
            ],
            options={
                'verbose_name': 'benefício de colaborador',
                'verbose_name_plural': 'benefícios de colaboradores',
                'ordering': ['colaborador__nome'],
                'unique_together': {('periodo', 'colaborador')},
            },
        ),
    ]
