# Generated by Django 5.2.7 on 2026-04-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamentocolaborador',
            old_name='vale_consumo',
            new_name='consumo_colaborador',
        ),
    ]
