# Generated by Django 5.2.7 on 2026-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha', '0002_remove_lancamentocolaborador_vale_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocolaborador',
            name='descontos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descontos'),
        ),
        migrations.AlterField(
            model_name='lancamentocolaborador',
            name='consumo_colaborador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='consumo do colaborador'),
        ),
    ]
